### ISSUE TITLE
Could not find  "<bench_name>_stats"  and  "<bench_name>_stats_power"  files

### ISSUE THREAD

**Issue by jerrysinha** [ysshao/ALADDIN#14]
I have downloaded the docker image of gem5-aladdin and only built the Aladdin. I am able to run the triad example and the following output files are generated:  triad_summary, out.csv, ddg_parse_progress.out.

But, I am not able to find the  "**<bench_name>_stats**"  and  "**<bench_name>_stats_power**"  files. 

Do I need to set any flags for generating the stats files?

**Comment by xyzsam** [comment]
Trying defining the DEBUG macro on the command line.

**Comment by jerrysinha** [comment]
Hi @xyzsam , Thanks for replying.

I tried to run the command as follows:
 /workspace/gem5-aladdin/src/aladdin/common/aladdin --DEBUG triad ../dynamic_trace.gz config_example

And, ofcourse it is not working!! 
How do I set the DEBUG macro?

**Comment by xyzsam** [comment]
Sorry I wasn't clear about this. You need to build Aladdin with the DEBUG macro defined. So just add -DDEBUG to CFLAGS. Alternatively, you can do `make debug` instead of `make` (under aladdin/src/common) which will add the DEBUG macro and -O0 for you.

**Comment by jerrysinha** [comment]
Thanks @xyzsam , I am able to generate the files.
