### ISSUE TITLE
Other SHOC benchmarks configuration examples

### ISSUE THREAD

**Issue by noureddine-as** [ysshao/ALADDIN#16]
Hello,
I'm new to Aladdin and Gem5-aladdin.
I have a little request, apparently, from the `SHOC` benchmark suite only the `triad` one has an example configuration file. It would be very useful (especially to understand the results in the papers) if some examples have been included to the other benchmarks (fft, gemm ...) ?

Thanks in advance!
Best regards,

**Comment by xyzsam** [comment]
Hi,

These scripts were only meant to be a reference. You should be able to write the config scripts to generate whatever sweeps you would like. The READMEs in both gem5-aladdin/sweeps and under the xenon repo itself should give you a very thorough overview of how to write config files. As an example, in shoc.xe:

"sweep unrolling for triad.triad.triad from 1 to 8"

means: in program triad, function triad, loop labeled triad, sweep the unrolling factor as 1,2,3,4,5,6,7,8.

**Comment by noureddine-as** [comment]
Okey @xyzsam , I'll inspire from the provided example with the python scripts in swweps.
Thank you!
