### ISSUE TITLE
bash: $../ALADDIN_HOME/common/aladdin: No such file or directory

### ISSUE THREAD

**Issue by lhanzhang123** [ysshao/ALADDIN#24]
I’m trying to build that framework ,
Q1 : I downloaded the docker image of gem5-aladdin , this error occurs on After setting the environment variables:
                       cd $ALADDIN_HOME/common
                       make 
Cmd show that /usr/bin/ld: cannot find -lboost_regex
collect2: error: ld returned 1 exit status
Makefile:86: recipe for target 'aladdin' failed
make: *** [aladdin] Error 1

Q2 :  I can’t find this file when i execute this command : $ALADDIN_HOME/common/aladdin triad ../dynamic_trace.gz config_example,That occurs on step 4. Run Aladdin .  
Cmd show that bash: $../ALADDIN_HOME/common/aladdin: No such file or directory

Hope u can answer my question .

Thank you !

**Comment by ochapeau** [comment]
Hi, I have the same issue as your Q1. How did you solved it ? Thanks !

**Comment by lhanzhang123** [comment]
u can try "sudo apt-get install libboost-regex-dev" this command

**Comment by ochapeau** [comment]
Thanks for your quick answer !
