### ISSUE TITLE
can't produce dynamic_trace.gz

### ISSUE THREAD

**Issue by lhanzhang123** [ysshao/ALADDIN#28]
it show dynamic_trace.gz: Starting to log at inst = 0. after executed ./xxx-instrumented , there are never get the stopping logging message . how i debug it ?

**Comment by xyzsam** [comment]
It's likely that you didn't set the WORKLOAD environment variable. You need to do that before building the instrumented binary. If that's not the issue, I'll need more information to help you debug. What are you trying to run? What OS/environment are you using?

**Comment by lhanzhang123** [comment]
i run my code on Docker . Actually , i m confused on WORKLOAD , is it setting all the subroutine except the main function ? 
The following is my header file and Makefile , github cant upload header file , so i convert to txt file .
And i have another problem about config file : A loop did not describe in config file v.s A loop unrolling , why the loop which did not describe that will execute faster than the loop unrolling , and i tried all the unrolling factor that can't reach the execution cycle . 
[kernel_tile4.txt](https://github.com/ysshao/ALADDIN/files/4727019/kernel_tile4.txt)
[Makefile.txt](https://github.com/ysshao/ALADDIN/files/4727020/Makefile.txt)
[VWA.txt](https://github.com/ysshao/ALADDIN/files/4727021/VWA.txt)
[Input_Tile1.txt](https://github.com/ysshao/ALADDIN/files/4727022/Input_Tile1.txt)
[Input_Tile2.txt](https://github.com/ysshao/ALADDIN/files/4727023/Input_Tile2.txt)
[Input_Tile3.txt](https://github.com/ysshao/ALADDIN/files/4727024/Input_Tile3.txt)
[Input_Tile4.txt](https://github.com/ysshao/ALADDIN/files/4727025/Input_Tile4.txt)
[Input_Tile5.txt](https://github.com/ysshao/ALADDIN/files/4727026/Input_Tile5.txt)
[Input_Tile6.txt](https://github.com/ysshao/ALADDIN/files/4727027/Input_Tile6.txt)
[Input_Tile7.txt](https://github.com/ysshao/ALADDIN/files/4727028/Input_Tile7.txt)
[Input_Tile8.txt](https://github.com/ysshao/ALADDIN/files/4727029/Input_Tile8.txt)
[kernel_tile1.txt](https://github.com/ysshao/ALADDIN/files/4727030/kernel_tile1.txt)
[kernel_tile2.txt](https://github.com/ysshao/ALADDIN/files/4727031/kernel_tile2.txt)
[kernel_tile3.txt](https://github.com/ysshao/ALADDIN/files/4727032/kernel_tile3.txt)



Thank you for reply !
