### ISSUE TITLE
A problem about running aladdin

### ISSUE THREAD

**Issue by lhanzhang123** [ysshao/ALADDIN#29]
i'm trying to run my code on Docker , i met a problem when i execute $ALADDIN_HOME/common/aladdin mac ../dynamic_trace.gz   config_example

cmd show :
 aladdin: ScratchpadDatapath.cpp:239: virtual void ScratchpadDatapath::stepExecutingQueue(): Assertion `partition.memory_type != dma && "Host memory accesses are not supported by standalone Aladdin!"' failed.

i have tried to trace the source code , but it's too difficult for me .

**Comment by xyzsam** [comment]
You need to make sure that every array you access in Aladdin is declared in your config file. Standalone Aladdin does not support host memory accesses (e.g. over DMA or cache).

We have Makefiles in aladdin/MachSuite which implement the entire tracing flow. You can take those and adapt them for your use.

**Comment by lhanzhang123** [comment]
thank you !
i will try agian
